### PR TITLE
fix: adjust documentation display

### LINKED ISSUE #124: GraphQL field descriptions in IntelliSense have broken syntax highlighting
In VS Code, GraphQL field descriptions in IntelliSense have broken syntax highlighting:

Screenshot 2023-12-05 at 5 00 18 PM

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Resolve #124 

There are probably more possible improvements, looking at what it produces from an urql TSDoc...

```json
  "body": {
    "kind": "alias",
    "kindModifiers": "declare",
    "start": {
      "line": 39,
      "offset": 1
    },
    "end": {
      "line": 39,
      "offset": 13
    },
    "displayString": "(alias) createClient(opts: ClientOptions): Client\nimport createClient",
    "documentation": [
      {
        "text": "Accepts `ClientOptions` and creates a `Client`.",
        "kind": "text"
      }
    ],
    "tags": [
      {
        "name": "param",
        "text": [
          {
            "text": "opts",
            "kind": "parameterName"
          },
          {
            "text": " ",
            "kind": "space"
          },
          {
            "text": "- A ",
            "kind": "text"
          },
          {
            "text": "{@link ",
            "kind": "link"
          },
          {
            "text": "ClientOptions",
            "kind": "linkName",
            "target": {
              "file": "/Users/jovi/Documents/SideProjects/GraphQLSP/node_modules/.pnpm/@urql+core@3.2.2_graphql@16.8.1/node_modules/@urql/core/dist/urql-core-chunk.d.ts",
              "start": {
                "line": 12,
                "offset": 1
              },
              "end": {
                "line": 133,
                "offset": 2
              }
            }
          },
          {
            "text": "}",
            "kind": "link"
          },
          {
            "text": " objects with options for the `Client`.",
            "kind": "text"
          }
        ]
      },
      {
        "name": "returns",
        "text": [
          {
            "text": "A ",
            "kind": "text"
          },
          {
            "text": "{@link ",
            "kind": "link"
          },
          {
            "text": "Client",
            "kind": "linkName",
            "target": {
              "file": "/Users/jovi/Documents/SideProjects/GraphQLSP/node_modules/.pnpm/@urql+core@3.2.2_graphql@16.8.1/node_modules/@urql/core/dist/urql-core-chunk.d.ts",
              "start": {
                "line": 440,
                "offset": 15
              },
              "end": {
                "line": 440,
                "offset": 58
              }
            }
          },
          {
            "text": "}",
            "kind": "link"
          },
          {
            "text": " instantiated with `opts`.",
            "kind": "text"
          }
        ]
      }
    ]
  }
```

### CODE REVIEW

File: packages/graphqlsp/src/quickInfo.ts [hunk 1]
```diff
@@ -87,16 +90,16 @@ export function getGraphQLQuickInfo(
...
         start: cursorPosition,
         length: 1,
       },
-      kindModifiers: '',
-      displayParts: Array.isArray(hoverInfo)
-        ? hoverInfo.map(item => ({ kind: '', text: item as string }))
-        : [{ kind: '', text: hoverInfo as string }],
-    };
+      kindModifiers: 'text',
+      documentation: Array.isArray(hoverInfo)
```
Comment (kitten) [inline packages/graphqlsp/src/quickInfo.ts:99]: I'm admittedly a bit confused about this. It looks like `displayString` may be reserved for code-like references, while `documentation` is only for "meta" information?

This could correspond to the hover string, where `displayString` might be displayed in monospace, while `documentation` is the smaller sans-serif text below it, if I'm not mistaken
