### PR TITLE
fix: support suggestions in type-conditions

### LINKED ISSUE #261: Suggestions for inline fragments
Inline fragments don't give suggestions.

# What doesn't work

```ts
... on 
```
I'd expect items there, but nothing comes up.

Screenshot 2024-03-08 at 1 54 33 PM

# Workaround

```ts
... on {}
```

If I add those opening and closing brackets, then go back with my cursor, they show up.

Screenshot 2024-03-08 at 1 55 00 PM
This does work though:

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes #261

### CODE REVIEW

File: test/e2e/fixture-project-tada/introspection.d.ts [hunk 1]
```diff
@@ -422,6 +422,10 @@ export type introspection = {
       {
         "kind": "SCALAR",
         "name": "Boolean"
+      },
+      {
+        "kind": "SCALAR",
+        "name": "Any"
```
Comment (JoviDeCroock) [inline test/e2e/fixture-project-tada/introspection.d.ts:428]:
```suggestion
```

**Review by kitten — APPROVED** [review]
