### PR TITLE
fix: test token-pos change

### LINKED ISSUE #190: Autocomplete broken for certain formatting
If I type the following (using this exact spacing) I get no autocomplete:

```tsx
const mutationDoc = graphql(`mutation MyMutation {
  
}
`)
```

I'm trying to get suggestions for mutation names. However, I just see this:

image

## Workaround

If I add a space before the closing braces, then the formatting does work:

image

Notice on `line 24`, there is now a space before the closing brace.

It's a bit inconsistent, but I can reproduce it like this:

https://github.com/0no-co/GraphQLSP/assets/13172299/abee5b45-44a9-448e-9741-1ed5380c0db3

Basically, it happens until some formatting changes.

### PR DESCRIPTION
**Pull request by JoviDeCroock**
fixes #190 

This worked on Windows but not on unix 😅

### CODE REVIEW

**Review by kitten — APPROVED** [review]

File: packages/graphqlsp/src/ast/token.ts [hunk 1]
```diff
@@ -22,8 +22,8 @@ export const getToken = (
 
   let foundToken: Token | undefined = undefined;
   for (let line = 0; line < input.length; line++) {
-    const lPos = cPos - 1;
-    const stream = new CharacterStream(input[line]);
+    const lPos = cPos;
+    const stream = new CharacterStream(input[line] + '\n');
```
Comment (llllvvuu) [inline packages/graphqlsp/src/ast/token.ts:26]: Could it be that this line by itself is enough to fix https://github.com/0no-co/GraphQLSP/issues/190, so that we don't need the [regression](https://github.com/0no-co/GraphQLSP/issues/15) from the line before it?
